architect:
  - dgroup

readers:
  - "urn:github:1651114"

assets:
  secret.xml: "dgroup/mvn-secret-settings#docker-unittests.xml"

merge:
  env:
      MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx512m"
  script:
    - mvn -Pqulice clean package
deploy:
  script: |
    mvn clean deploy -Pqulice --errors --settings ../secret.xml
release:
  script: |
    mvn versions:set "-DnewVersion=$tag"
    git commit -am "$tag"
    mvn -Pqulice clean package
    mvn -Prelease -s ../secret.xml github-release:release