architect:
  - dgroup

readers:
  - "urn:github:1651114"

assets:
  secret.xml: "dgroup/mvn-secret-settings#docker-unittests.xml"

merge:
  env:
      MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx512m"
  script:
    - mvn -Pqulice -Ddocker_installed=no clean package

deploy:
  script: |
    env
    echo "Tag is $tag"
    mvn -Prelease -s ../secret.xml github-release:release

release:
  script: |
    mvn versions:set "-DnewVersion=$tag"
    git commit -am "$tag"
    mvn -Pqulice -Ddocker_installed=no clean package