architect:
  - dgroup

readers:
  - "urn:github:1651114"

assets:
  settings.xml: "dgroup/mvn-secret-settings#settings.xml.asc"
  9B6EC9DB.gpg: "dgroup/mvn-secret-settings#9B6EC9DB.gpg.asc"

merge:
  env:
      MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx512m"
  script:
    - mvn -Pqulice clean package
deploy:
  script: |
    mvn clean deploy -Pqulice --errors --settings ../settings.xml
release:
  env:
    gpg.homedir: /home/r
  script: |
    mvn versions:set "-DnewVersion=$tag"
    git commit -am "$tag"
    mvn -V -P qulice,github,ossrh -s ../settings.xml clean install