#
# Check configuration online:
#   https://lint.travis-ci.org

language: java

notifications:
  slack: jclubteam:upRZaAFk2dZkFTVmpFIVOVOB

sudo: required

services:
  - docker

before_install:
  - docker pull openjdk:9.0.1-11

cache:
  directories:
    - $HOME/.m2

script:
  - set -e
  - mvn -DskipTests clean install dependency:resolve-plugins dependency:go-offline
  - mvn -Pqulice test
  - mvn -Psonar sonar:sonar -Dsonar.organization=dgroup-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=9006f420405fb08ec8373a62083221c9c3f83fc0

env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"

jdk:
  - oraclejdk8

after_success:
  - "bash <(curl -s https://codecov.io/bash)"
